changelog:
  exclude:
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: "Breaking changes"
      labels:
        - breaking-change
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "API updates"
      labels:
        - api-update
    - title: "Features"
      labels:
        - feature
        - enhancement
    - title: "Performance improvements"
      labels:
        - efficiency
    - title: "Maintenance"
      labels:
        - refactor
        - cleanup
        - unit tests
        - error handling
        - type checking
    - title: "Other Changes"
      labels:
        - misc
